# Build script
environment:
  website_name: appychristmas
  website_psw:
    secure: AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAA024zePPvCk66gydYIQs9yAAAAAACAAAAAAADZgAAwAAAABAAAABdO1V9SSQQoMCGl1OpJVRyAAAAAASAAACgAAAAEAAAAJ4ui3RwZcBdTj0PJ9x7+M2AAAAAWJkbhdNVRaoOtsVVGo4GOt1r2wT4ddwXk6YdbrWX/UOjzx/S3nEgYKj8pajR7TbMwRYWo1xyTYciJcri/XQWuxsqY59uQGQHmKQnFoB+aagaAoKcT7dKx3I0P+iU7O9C1obZizpP5TAXC+4mPyI9VxCSGfSFC+vOdrhcZe8JFEgUAAAAi1xSyetshcwiMGM/VaPFRCyL0+U=

init:
  - git config --global core.autocrlf true

# Build script
build_script:
  - ps: .\build.ps1 -Target "AppVeyor" -Configuration "Release"

# Tests
test: off

# Branches to build
branches:
  # Whitelist
  only:
    - develop
    - master
    - /r/.*/
    - /release/.*/
    - /hotfix/.*/

# Build cache
cache:
- tools -> build.cake

deploy_script:
- '"C:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe" -source:IisApp=''%appveyor_build_folder%\artifacts'' -dest:IisApp=''%website_name%'',ComputerName=''https://%website_name%.scm.azurewebsites.net/msdeploy.axd'',UserName=''$%website_name%'',Password=''%website_psw%'',IncludeAcls=''False'',AuthType=''Basic'' -verb:sync -enablerule:AppOffline -enableRule:DoNotDeleteRule -retryAttempts:2'