# Build script
environment:
  website_name: appychristmas
  website_psw:
    secure: AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAA024zePPvCk66gydYIQs9yAAAAAACAAAAAAADZgAAwAAAABAAAAB+S5P1aJBIWhhkE+KiLdv0AAAAAASAAACgAAAAEAAAAJPtZ5ujVMi64DpIJh8lHv4YAAAApa0suOy34O14yJnlFRxU5MqVR8XtH/v6FAAAABr7QCyAlMkCTbyPuHaAtJgjl4w8

init:
  - git config --global core.autocrlf true

# Build script
build_script:
  - ps: .\build.ps1 -Target "AppVeyor" -Configuration "Release"

# Tests
test: off

# Branches to build
branches:
  # Whitelist
  only:
    - develop
    - master
    - /r/.*/
    - /release/.*/
    - /hotfix/.*/
    - netcore11
    
# Build cache
cache:
- tools -> build.cake

artifacts:
- path: artifacts
  name: appychristmas

deploy:
- provider: WebDeploy
  server: appychristmas.scm.azurewebsites.net:443
  website: appychristmas
  username: $appychristmas
  password:
    secure: BpL57VpY3VKqUh8QdabghCr/l7jQP0L+6VhBRSc6CSPAgGmGBu78hOny9D+hg+AFaRPA/lNGdiT003Zr7F1qbQ==
  artifact: appychristmas
  aspnet_core: true
  remove_files: true
  aspnet_core_force_restart: true