# Build script
init:
  - git config --global core.autocrlf true

# Build script
build_script:
  - ps: .\build.ps1 -Target "AppVeyor" -Configuration "Release"

# Tests
test: off

# Branches to build
branches:
  # Whitelist
  only:
    - master
    - netcore11
    - netcore11-ef

# Build cache
cache:
- tools -> build.cake

artifacts:
- path: artifacts
  name: appychristmasef

deploy:
- provider: WebDeploy
  server: https://appychristmasef.scm.azurewebsites.net:443/msdeploy.axd?site=appychristmasef
  website: appychristmasef
  username: $appychristmasef
  password:
    secure: otmgf0ZgnmsJkG1b7xDwzkdy1JXr4pNLrMulnDjvR0JL8Q7n3rGwNmW2QxAj
  artifact: appychristmasef
  aspnet_core: true
  remove_files: true
  aspnet_core_force_restart: true