# Build script
init:
  - git config --global core.autocrlf true

# Use 2017 Image :)
image: 
  - Visual Studio 2017 RC

# Build script
build_script:
  - ps: .\build.ps1 -Target "AppVeyor" -Configuration "Release"

# Tests
test: off

# Branches to build
branches:
  # Whitelist
  only:
    - master
    - netcore11
    - netcore11-ef

# Build cache
cache:
- tools -> build.cake

artifacts:
- path: artifacts
  name: appychristmasef