# Build script
environment:
  website_name: appychristmas
  website_psw:
    secure: AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAA024zePPvCk66gydYIQs9yAAAAAACAAAAAAADZgAAwAAAABAAAAB+S5P1aJBIWhhkE+KiLdv0AAAAAASAAACgAAAAEAAAAJPtZ5ujVMi64DpIJh8lHv4YAAAApa0suOy34O14yJnlFRxU5MqVR8XtH/v6FAAAABr7QCyAlMkCTbyPuHaAtJgjl4w8

init:
  - git config --global core.autocrlf true

# Build script
build_script:
  - ps: .\build.ps1 -Target "AppVeyor" -Configuration "Release"

# Tests
test: off

# Branches to build
branches:
  # Whitelist
  only:
    - master
    - netcore11
    - netcore11-ef

# Build cache
cache:
- tools -> build.cake

artifacts:
- path: artifacts
  name: appychristmas